spring.application.name=user
server.port=0
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}${random.int}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=false
